# Урок 4. Видеоурок. Визуализация данных в Matplotlib.

## Задание на повторение материала

In [2]:
import numpy as np
import pandas as pd

### № 1

In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

## № 2

In [16]:
a2_1 = a.reshape(2,6)
a2_2 = a.reshape(3,4)
a2_3 = a.reshape(4,3)
a2_4 = a.reshape(6,2)
a2_5 = a.reshape(12,1)

In [20]:
print(a2_1,'\n\n', a2_2,'\n\n', a2_3, '\n\n', a2_4, '\n\n', a2_5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


## № 3

In [24]:
a3_1 = a.reshape(2,-1)
a3_2 = a.reshape(3,-1)
a3_3 = a.reshape(4,-1)
a3_4 = a.reshape(-1,2)
a3_5 = a.reshape(-1,1)

In [25]:
print(a3_1,'\n\n', a3_2,'\n\n', a3_3, '\n\n', a3_4, '\n\n', a3_5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


## № 4

In [28]:
a3_5.ndim

2

### не можем

## № 5

In [36]:
a5 = np.random.randn(3, 4)
print(a5, '\n\n', a5.size)

[[-0.34694676  0.59602064  0.27732898 -0.41832494]
 [ 0.28125116 -0.57124734 -0.14796427 -0.32424813]
 [ 0.16573375 -0.4400928  -1.9176093   0.74386042]] 

 12


In [37]:
a5_flat = a5.flatten()
print(a5_flat, '\n\n', a5_flat.size)

[-0.34694676  0.59602064  0.27732898 -0.41832494  0.28125116 -0.57124734
 -0.14796427 -0.32424813  0.16573375 -0.4400928  -1.9176093   0.74386042] 

 12


## № 6

In [3]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [8]:
a.shape

(12,)

In [10]:
a.size

12

## № 7

In [12]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [6]:
b.resize(1,10)

In [7]:
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


In [9]:
b.shape

(1, 10)

In [11]:
b.size

10

## № 8

In [14]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

In [15]:
v = np.vstack((a, b))

In [16]:
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

## № 9

In [41]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
A_t = A.T
print(A_t)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [44]:
B = A.dot(A_t)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [45]:
print(np.linalg.det(B))

0.0


### Определитель матрицы равен 0. Обратной матрицы не существует

## № 10

In [47]:
np.random.seed(42)

## № 11

In [48]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

##  № 12

In [49]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [60]:
D = C + B * 10
D

array([[  56,  143,  242,  334],
       [ 150,  507,  872, 1224],
       [ 236,  869, 1492, 2126],
       [ 330, 1230, 2127, 3024]])

In [61]:
d = np.linalg.det(D)

print(d)

-1741607.9999999756


In [62]:
r = np.linalg.matrix_rank(D)

print(r)

4


In [63]:
D_inv = np.linalg.inv(D)

print(D_inv)

[[ 0.135368   -0.09412681 -0.0250975   0.04079219]
 [-0.17297808  0.16351785  0.1740805  -0.16946638]
 [-0.05802224  0.09496052 -0.10651536  0.04285695]
 [ 0.09639712 -0.12303113  0.00685229  0.03466452]]


## № 13

In [64]:
ind1 = np.where(D_inv < 0)
ind1

(array([0, 0, 1, 1, 2, 2, 3], dtype=int64),
 array([1, 2, 0, 3, 0, 2, 1], dtype=int64))

In [65]:
D_inv[ind1] = 0
D_inv

array([[0.135368  , 0.        , 0.        , 0.04079219],
       [0.        , 0.16351785, 0.1740805 , 0.        ],
       [0.        , 0.09496052, 0.        , 0.04285695],
       [0.09639712, 0.        , 0.00685229, 0.03466452]])

In [66]:
ind2 = np.where(D_inv > 0)
ind2

(array([0, 0, 1, 1, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 3, 1, 2, 1, 3, 0, 2, 3], dtype=int64))

In [67]:
D_inv[ind2] = 1
D_inv

array([[1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 1.]])

In [68]:
E = np.where(D_inv, B, C)
E

array([[  5,   3,  12,  32],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212, 302]])