In [24]:
import numpy as np
a = np.array([[1, 6], [2, 8],[3, 11], [3, 10], [1, 7]])

In [25]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [26]:
mean_a = a.mean(axis=0)

In [27]:
mean_a

array([2. , 8.4])

In [28]:
a_centered = a - mean_a

In [29]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [30]:
a_centered[:,1]

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [33]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]

In [35]:
result = a_centered_sp/(5-1)

In [36]:
result

2.0