## Урок 2. Тема “Вычисления с помощью Numpy”

## Задание № 1

In [12]:
import numpy as np
a = np.array([[1, 6], [2, 8],[3, 11], [3, 10], [1, 7]])

In [13]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [14]:
mean_a = a.mean(axis=0)

In [15]:
mean_a

array([2. , 8.4])

## Задание № 2

In [16]:
a_centered = a - mean_a

In [17]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [18]:
a_centered[:,1]

array([-2.4, -0.4,  2.6,  1.6, -1.4])

## Задание № 3

In [19]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]

In [20]:
result = a_centered_sp/(5-1)

In [21]:
result

2.0

## Задание № 4

In [22]:
a_tr = np.transpose(a)

In [23]:
a_tr

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [24]:
a_cov = np.cov(a_tr)

In [25]:
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [26]:
result_cov = a_cov[0, 1]

In [27]:
result_cov

2.0

In [28]:
result == result_cov

True